#!/usr/bin/env python

import argparse
from glue_etl import glue

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()

run_parser = subparsers.add_parser('init', help="Initialize a Glue Job")
run_parser.set_defaults(handler=glue.init_job)

deploy_parser = subparsers.add_parser('deploy', help="Deploy a job to AWS Glue")
deploy_parser.set_defaults(handler=glue.deploy_job)

run_parser = subparsers.add_parser('run', help="Run a Glue Job")
run_parser.set_defaults(handler=glue.run_job)

if __name__ == '__main__':
    args = parser.parse_known_args()
    if hasattr(args[0], 'handler'):
        if args[0].handler is glue.run_job:
            args[0].handler(args[1])
        else:
            args[0].handler()
    else:
        parser.print_help()